%VULKAN_SDK%/bin/glslc.exe ./shaders/simple_shader.vert -o ./shaders/simple_shader.vert.spv
%VULKAN_SDK%/bin/glslc.exe ./shaders/simple_shader.frag -o ./shaders/simple_shader.frag.spv
%VULKAN_SDK%/bin/glslc.exe ./shaders/point_line_shader.vert -o ./shaders/point_line_shader.vert.spv
%VULKAN_SDK%/bin/glslc.exe ./shaders/point_line_shader.frag -o ./shaders/point_line_shader.frag.spv
%VULKAN_SDK%/bin/glslc.exe ./shaders/button_shader.vert -o ./shaders/button_shader.vert.spv
%VULKAN_SDK%/bin/glslc.exe ./shaders/control_point_shader.vert -o ./shaders/control_point_shader.vert.spv
%VULKAN_SDK%/bin/glslc.exe ./shaders/phong_shader.frag -o ./shaders/phong_shader.frag.spv
%VULKAN_SDK%/bin/glslc.exe ./shaders/point_light.vert -o ./shaders/point_light.vert.spv
%VULKAN_SDK%/bin/glslc.exe ./shaders/point_light.frag -o ./shaders/point_light.frag.spv
%VULKAN_SDK%/bin/glslc.exe ./shaders/texture_shader.frag -o ./shaders/texture_shader.frag.spv
%VULKAN_SDK%/bin/glslc.exe ./shaders/texture_shader.vert -o ./shaders/texture_shader.vert.spv
%VULKAN_SDK%/bin/glslc.exe ./shaders/texture_button_shader.frag -o ./shaders/texture_button_shader.frag.spv